import scrapy


class ZerozeroPlayerItem(scrapy.Item):
    slug = scrapy.Field()
    nome = scrapy.Field()
    data_nascimento = scrapy.Field()
    idade = scrapy.Field()
    pais_nascimento = scrapy.Field()
    naturalidade = scrapy.Field()
    nacionalidade = scrapy.Field()
    dupla_nacionalidade = scrapy.Field()
    ligacoes = scrapy.Field()
    parentescos = scrapy.Field()
    situacao = scrapy.Field()
    internacionalizacoes_a = scrapy.Field()
    altura = scrapy.Field()
    peso = scrapy.Field()
    posicoes = scrapy.Field()
    clube_atual = scrapy.Field()
    valor_mercado = scrapy.Field()
    resumo = scrapy.Field()
    historico = scrapy.Field()
    transferencias_entradas = scrapy.Field()
    transferencias_saidas = scrapy.Field()
    factos = scrapy.Field()
    top = scrapy.Field()
    fotografias = scrapy.Field()
    sala_trofeus = scrapy.Field()
    partilhou_plantel_com = scrapy.Field()
    fotos_perfil = scrapy.Field()
    raio_x_url = scrapy.Field()
    profile_url = scrapy.Field()
